### ISSUE TITLE
bns.yaml file 

### ISSUE THREAD

**Issue by binovatyv** [taraldefi/taral#678]
## Current Behavior

Run the command 
  docker-compose -f docker\bns.yaml build 
will fail

## Expected Behavior
Should Build and show the results
   Building bns-data
   [+] Building 13.9s (15/15) FINISHED

  Fix 
    Replace context: ./provisioning/bns in  bns.yaml file 
    with  context: ./provisioning/private-testnet/bns

## Environment

- Version: 
- Platform: 
- Node.js Version:

**Comment by dorucioclea** [comment]
Hey, you're right! 😄 I planned to clean up that directory for some time, will address this next! Thank you 👌

**Comment by binovatyv** [comment]
> Hey, you're right! 😄 I planned to clean up that directory for some time, will address this next! Thank you 👌

Besides that, I was able to get your code and running in my local. Please advise how can I help
